### ISSUE TITLE
Orchestrator - Throws an Error

### ISSUE THREAD

**Issue by superKalo** [stackdot/sketch-preview#3]
Hi, I followed the installation instructions and installed the `sketch-preview` globally, but when I run:
```
sketch-preview --input=myfile.sketch
```

I get the following error:

```bash
Generating Sketch Preview... Please be patient
build
/Users/MyUser/.nvm/versions/node/v7.4.0/lib/node_modules/sketch-preview/node_modules/orchestrator/index.js:153
            throw err;
            ^

Error: Command failed: /Users/MyUser/.nvm/versions/node/v7.4.0/lib/node_modules/sketch-preview/sketchtool/bin/sketchtool export artboards --include-symbols --output=/Users/MyUser/Sites/my-project/_artboards --scales=2.0 --use-id-for-name=YES --format=jpg /Users/MyUser/Sites/my-project/myfile.sketch
2017-07-31 16:20:18.377 sketchtool[69584:3264514] DB Error: 26 "file is encrypted or is not a database"
2017-07-31 16:20:18.378 sketchtool[69584:3264514] DB Query: PRAGMA journal_mode=OFF
2017-07-31 16:20:18.378 sketchtool[69584:3264514] DB Path: /Users/MyUser/Sites/my-project/myfile.sketch
Failed to open document file:///Users/MyUser/Sites/my-project/myfile.sketch


    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
[1]    69583 segmentation fault  sketch-preview --input=myfile.sketch
```

The file I am trying to preview is not encrypted.

I am running NodeJS v7.4.0 on MacOS Sierra.

I don't have a valid license for Sketch, is this an issue?

**Comment by ilp64** [comment]
@superKalo I have the same issue. You can use [lastet sketchtool](https://www.sketchapp.com/tool/) in place of `sketch-preview/sketchtool/bin/sketchtool` . This should work.
